name: ci-golang-workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1
    - name: Run go test
      run: go test
    - name: Run code
      run: go run math.go